[System Base Info]
#支持的下注档位
BetScopes = 100000,200000,500000,1000000,2000000,5000000,10000000,20000000

[Game Info]
#配置文件版本
Version=101
#Cluster至少5个横向或纵向相连的同类图标起奖
ClusterMinimum=5
#免费游戏触发图标ID
ScatterId=0
#Super Scatter原始图标与Scatter相同，使用ID 0
SuperScatterSourceId=0
#转化成功后使用ID 13区分Super Scatter
SuperScatterId=13
#每个Scatter独立转化为Super Scatter的概率，200/10000=1/50
SuperScatterProbability=200
#Scatter出现数量权重，下标0-3分别表示出现0-3个
ScatterCountProbability=1000,100,50,5
#Base无Scatter且无奖时，Bonus数量0/1的权重
BaseNoWinBonusCountProbability=80,20
#Base无Scatter且有奖时，Bonus数量0/1的权重
BaseWinBonusCountProbability=90,10
#Free已有金框时，Bonus数量0/1的权重
FreeGoldenBonusCountProbability=60,40
#Free没有金框时，Bonus数量0/1的权重
FreeNoGoldenBonusCountProbability=30,70
#每个掉落图标替换结果权重：不替换/Scatter/Bonus
DropSpecialSymbolProbability=998,1,1
#金色玩法Bonus及结算图标统一使用ID 2
FeatureSymbolId=2
#普通免费、超级免费初始次数
FreeSpinCounts=10,10
#下标为Scatter数量；2个追加2次，3个追加4次
FreeSpinRetrigger=0,0,2,4
