[MAIN]
#基础轴占位配置，轴内容与xml_game_server.conf中的ReelConfig一致
VERSION=101

[GENERAL_1]
#基本几率：正常盘、特殊盘、固定盘、0几率盘
BASE_RATE=1000,0,0,0

NORMAL_ROLL_1=8,6,2,2,9,9,7,5,5,0,9,8,8,6,3,3,9,7,7,4,4,0,9,6
SP_ROLL_1=8,6,2,2,9,9,7,5,5,0,9,8,8,6,3,3,9,7,7,4,4,0,9,6

FIX_DISORDER=0
FIX_NUM=0
ZERO_DISORDER=0
ZERO_NUM=0
