[System Base Info]
#配置文件版本，当版本改变时重新读取配置
VERSION = 102
#开启的游戏功能版本号
OPEN_GAME_VER = 6
#日使用最大数量(注意:不要超过100000000)
DAY_USE_MAX_NUM = 99999

[SLOT_PROP_INFO_1]
#道具ID
PROP_ID = 1357001
#道具类型(-2:免费游戏卡)
PROP_TYPE = -2
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 2
#道具属性2(道具卡品质)
PROP_BUFF_2 = 1
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 100000
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_2]
#道具ID
PROP_ID = 1357002
#道具类型(-2:免费游戏卡)
PROP_TYPE = -2
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 4
#道具属性2(道具卡品质)
PROP_BUFF_2 = 2
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 100000000
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_3]
#道具ID
PROP_ID = 1357003
#道具类型(-2:免费游戏卡)
PROP_TYPE = -2
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 5
#道具属性2(道具卡品质)
PROP_BUFF_2 = 3
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 250000000
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_4]
#道具ID
PROP_ID = 1357004
#道具类型(-2:免费游戏卡)
PROP_TYPE = -2
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 7
#道具属性2(道具卡品质)
PROP_BUFF_2 = 4
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 1000000000
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_5]
#道具ID
PROP_ID = 1357005
#道具类型(-2:免费游戏卡)
PROP_TYPE = -2
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 8
#道具属性2(道具卡品质)
PROP_BUFF_2 = 5
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 1250000000
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_6]
#道具ID
PROP_ID = 3010105
#道具类型(-2:免费游戏卡)
PROP_TYPE = -5
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 4
#道具属性2(道具卡品质)
PROP_BUFF_2 = 10
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 0
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_7]
#道具ID
PROP_ID = 3010106
#道具类型(-2:免费游戏卡)
PROP_TYPE = -5
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 5
#道具属性2(道具卡品质)
PROP_BUFF_2 = 10
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 0
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_8]
#道具ID
PROP_ID = 3010107
#道具类型(-2:免费游戏卡)
PROP_TYPE = -5
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 6
#道具属性2(道具卡品质)
PROP_BUFF_2 = 10
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 0
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0

[SLOT_PROP_INFO_9]
#道具ID
PROP_ID = 3010108
#道具类型(-2:免费游戏卡)
PROP_TYPE = -5
#游戏ID
GAME_ID = 357
#道具属性1(道具类型为-2则表示押注值索引)
PROP_BUFF_1 = 7
#道具属性2(道具卡品质)
PROP_BUFF_2 = 10
#道具属性3(道具卡价值，大于0才能购买，需要和后台配置保持一致)
PROP_BUFF_3 = 0
#道具属性4(预留数字,可以不配)
PROP_BUFF_4 = 0
#道具属性5(预留数字,可以不配)
PROP_BUFF_5 = 0
#道具属性6(预留字符串,可以不配)
PROP_BUFF_6 = 0,0,0,0