[MAIN]
#配置文件版本
VERSION=103
#symbol id范围为0-9；0是Bonus，1未使用，2-9可下注
ITEM_COUNT=10
#每个symbol的下注必须为BaseBet的正整数倍
BaseBet=100000

#symbol 2-9分别对应八个水果图标的基础奖值
ITEM_PRIZE_2=2000000
ITEM_PRIZE_3=800000
ITEM_PRIZE_4=600000
ITEM_PRIZE_5=400000
ITEM_PRIZE_6=400000
ITEM_PRIZE_7=300000
ITEM_PRIZE_8=200000
ITEM_PRIZE_9=100000
