[MAIN]
#配置文件版本
VERSION=101
#列数(竖)
COL_COUNT=1
#行数（横）
ROW_COUNT=1
#物件个数
ITEM_COUNT=10
#当前配置的奖励倍率(物件倍率/全盘倍率;实际奖励要除以该值)
PRIZE_RATE=1
#每个symbol的下注必须为BaseBet的正整数倍
BaseBet=10000

#symbol 2-9的基础奖值，派彩时与X相乘
ITEM_PRIZE_2=10000
ITEM_PRIZE_3=10000
ITEM_PRIZE_4=10000
ITEM_PRIZE_5=10000
ITEM_PRIZE_6=10000
ITEM_PRIZE_7=10000
ITEM_PRIZE_8=10000
ITEM_PRIZE_9=10000

#连线类型(1.左边连列 2.左边连线 3.左右连线)
LINE_MODE=4

#scatter类型
#1、按列开始找在列上出现的scatter(60条线，全线)
SCATTER_MODE=1
#scatterId号
SCATTER_ID=0