[System Base Info]
# 自动Spin次数选项
AutoSpinTimes = 10,100,500,-1,-2
# 大奖等级倍数
BigWinGrade = 10,20,50
NewBigWinGrade = 5,10,20,50,100,500
# 每条线押注
BetPerReel = 1,1,1,1,1,1,1,1,1
# 押注档位
BetScopes = 10,20,50,100,200,500,1000,2000,2500
# 解锁押注注册时间
BetUnLockRegTime = 2000/09/09 08:00:00
# 解锁押注等级
BetUnLockLevel = 5,5,5,5,5,5,5,5,0
# 解锁押注VIP等级
BetUnLockVip = 1,1,1,1,1,1,1,1,2

[Game Info]
# 配置版本号
Version=103

# 选免费次数与倍乘
FREE_COUNT_LIST = 24,12,8,6
FREE_MULTI_LIST_1 = 1,2,3,5
FREE_MULTI_LIST_2 = 2,4,6,10
FREE_MULTI_LIST_3 = 3,6,9,15
FREE_MULTI_LIST_4 = 4,8,12,20
FREE_RANDOM_COUNT_WEIGHTS = 2,3,4,5
FREE_RANDOM_MULTI_WEIGHTS = 11,8,8,6

# 大奖预警
Bigwin_Pre_Win_Range = 50,100,200
Bigwin_Pre_Rate = 3000,5000,9000

# BASE赢钱框倍乘升级概率（万分比）
WinBoxLevelUpRate=2000,40,8,2
# 赢钱框升级倍数序列
WinBoxLevelMultiple_1=1,2,3,5
WinBoxLevelMultiple_2=2,4,6,10
WinBoxLevelMultiple_3=3,6,9,15
WinBoxLevelMultiple_4=4,8,12,20

# 免费游戏最大次数
FreeMaxGameNum = 99
# 主游戏最大消除次数
Base_Max_EliTimes = 10
# 免费游戏最大消除次数
Free_Max_EliTimes = 10

# 控制类型0：免费整轮最大赢分倍数
Free_Max_TotalBet = 5000
# 主游戏第2/3/4列转金色概率（万分比）
GoldSymbolWeight = 750,600,730
# 免费第2/3/4列转金色概率（第3列固定10000）
FreeGoldSymbolWeight_1 = 450,10000,550
FreeGoldSymbolWeight_2 = 450,10000,550
FreeGoldSymbolWeight_3 = 500,10000,600
FreeGoldSymbolWeight_4 = 500,10000,600
# 保底触发剩余Spin阈值（对应FREE_COUNT_LIST各档）
Gua_Last_Spins_List = 12,6,3,2
# 触发主游戏倍乘升级后，2/3/4列转化成金色symbol的概率（万分比）
LevelUpGoldWeight = 1000,1000,1000

[4]
# 控制类型0：免费整轮最大赢分倍数
Free_Max_TotalBet = 10000
# 主游戏第2/3/4列转金色概率（万分比）
GoldSymbolWeight = 750,600,730
# 免费第2/3/4列转金色概率（第3列固定10000）
FreeGoldSymbolWeight_1 = 450,10000,550
FreeGoldSymbolWeight_2 = 450,10000,550
FreeGoldSymbolWeight_3 = 500,10000,600
FreeGoldSymbolWeight_4 = 500,10000,600
# 保底触发剩余Spin阈值（对应FREE_COUNT_LIST各档）
Gua_Last_Spins_List = 12,6,3,2
# 触发主游戏倍乘升级后，2/3/4列转化成金色symbol的概率（万分比）
LevelUpGoldWeight = 1000,1000,1000

[8]
Free_Max_TotalBet = 101
GoldSymbolWeight =300,1000,300
FreeGoldSymbolWeight_1 = 450,10000,550
FreeGoldSymbolWeight_2 = 450,10000,550
FreeGoldSymbolWeight_3 = 500,10000,600
FreeGoldSymbolWeight_4 = 500,10000,600
Gua_Last_Spins_List = 12,6,3,2
LevelUpGoldWeight = 1000,1000,1000

[12]
Free_Max_TotalBet = 20
GoldSymbolWeight =100,200,100
FreeGoldSymbolWeight_1 = 450,10000,550
FreeGoldSymbolWeight_2 = 450,10000,550
FreeGoldSymbolWeight_3 = 500,10000,600
FreeGoldSymbolWeight_4 = 500,10000,600
Gua_Last_Spins_List = 12,6,3,2
LevelUpGoldWeight = 1000,1000,1000

[13]
Free_Max_TotalBet = 10000
GoldSymbolWeight =950,900,950
FreeGoldSymbolWeight_1 = 650,10000,550
FreeGoldSymbolWeight_2 = 650,10000,550
FreeGoldSymbolWeight_3 = 700,10000,600
FreeGoldSymbolWeight_4 = 700,10000,600
Gua_Last_Spins_List = 12,6,3,2
LevelUpGoldWeight = 1000,1000,1000

[14]
Free_Max_TotalBet = 10000
GoldSymbolWeight =750,600,730
FreeGoldSymbolWeight_1 = 650,10000,550
FreeGoldSymbolWeight_2 = 650,10000,550
FreeGoldSymbolWeight_3 = 700,10000,600
FreeGoldSymbolWeight_4 = 700,10000,600
Gua_Last_Spins_List = 12,6,3,2
LevelUpGoldWeight = 1000,1000,1000

[17]
FreeMaxGameNum = 50
Free_Max_TotalBet = 1000
GoldSymbolWeight =750,600,730
FreeGoldSymbolWeight_1 = 450,10000,550
FreeGoldSymbolWeight_2 = 450,10000,550
FreeGoldSymbolWeight_3 = 500,10000,600
FreeGoldSymbolWeight_4 = 500,10000,600
Gua_Last_Spins_List = 12,6,3,2
LevelUpGoldWeight = 1000,1000,1000
