[System Base Info]
#相同配置
AutoSpinTimes = 10,100,500,-1,-2
#第四个参数为super洗分匀速到加速的临界值
BigWinGrade = 10,20,50
NewBigWinGrade = 5,10,20,50,100,500
BetPerReel = 10,10,10,10,10,10,10,10,10
BetScopes = 10,20,50,100,200,500,1000,2000,2500
#解锁押注配置(注册时间+玩家等级+玩家VIP等级)
#解锁押注注册时间,在此时间之后注册的才走配置
#解锁押注玩家等级,达到等级解锁(VIP等级满足此项不生效)
#解锁押注玩家VIP等级,达到等级解锁(不需要判断玩家等级)
BetUnLockRegTime = 2000/09/09 08:00:00
BetUnLockLevel = 5,5,5,5,5,5,5,5,0
BetUnLockVip = 0,0,0,0,0,0,0,0,2

[Game Info]
#版本号，每次改变下面配置需要改变
Version=107

#赢分框升级倍数,填写赢分框的总倍数
WinBoxLevelMultiple=1,2,3,5
#免费游戏最大次数 ,不允许超过该次数
FreeMaxGameNum = 99
#主游戏最大消除次数，不允许超过该消除次数（如果为0则不砍分）
MainMaxRoundNum = 10
#免费游戏最大消除次数，不允许超过该消除次数（如果为0则不砍分）
FreeMaxRoundNum = 10
#根据档位走不同[GENERAL_]滚轮
BetGeneralCtrl =1,1,1,1,1,1,1,1,1,1,1,1
 
[0]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 5000

# base中进入jp的概率
WIN_JP_PROBABILITY=0.001
# 赢得的JP的倍数，实际赢得的JP要乘以该值
WIN_JP_MULTIPLE=5000, 100, 50, 20
# 赢得每种JP的概率，相加为总概率
WIN_JP_TYPE_PROBABILITY=1, 5, 100, 500

# free的倍乘
FREE_MULTIPLE=2
# free的倍乘概率，相加为总概率
FREE_MULTIPLE_PROBABILITY=100
# Super free的倍乘
SUPER_FREE_MULTIPLE=6, 8, 15
# super free的倍乘概率，相加为总概率
SUPER_FREE_MULTIPLE_PROBABILITY=100, 50, 10

[4]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 10000

# base中进入jp的概率
WIN_JP_PROBABILITY=0.001
# 赢得的JP的倍数，实际赢得的JP要乘以该值
WIN_JP_MULTIPLE=5000, 100, 50, 20
# 赢得每种JP的概率，相加为总概率
WIN_JP_TYPE_PROBABILITY=1, 5, 100, 500

# free的倍乘
FREE_MULTIPLE=2
# free的倍乘概率，相加为总概率
FREE_MULTIPLE_PROBABILITY=100
# Super free的倍乘
SUPER_FREE_MULTIPLE=6, 8, 15
# super free的倍乘概率，相加为总概率
SUPER_FREE_MULTIPLE_PROBABILITY=100, 50, 10

[8]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 101

# base中进入jp的概率
WIN_JP_PROBABILITY=0.001
# 赢得的JP的倍数，实际赢得的JP要乘以该值
WIN_JP_MULTIPLE=5000, 100, 50, 20
# 赢得每种JP的概率，相加为总概率
WIN_JP_TYPE_PROBABILITY=1, 5, 100, 500

# free的倍乘
FREE_MULTIPLE=2
# free的倍乘概率，相加为总概率
FREE_MULTIPLE_PROBABILITY=100
# Super free的倍乘
SUPER_FREE_MULTIPLE=6, 8, 15
# super free的倍乘概率，相加为总概率
SUPER_FREE_MULTIPLE_PROBABILITY=100, 50, 10

[12]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 20

# base中进入jp的概率
WIN_JP_PROBABILITY=0.001
# 赢得的JP的倍数，实际赢得的JP要乘以该值
WIN_JP_MULTIPLE=5000, 100, 50, 20
# 赢得每种JP的概率，相加为总概率
WIN_JP_TYPE_PROBABILITY=1, 5, 100, 500

# free的倍乘
FREE_MULTIPLE=2
# free的倍乘概率，相加为总概率
FREE_MULTIPLE_PROBABILITY=100
# Super free的倍乘
SUPER_FREE_MULTIPLE=6, 8, 15
# super free的倍乘概率，相加为总概率
SUPER_FREE_MULTIPLE_PROBABILITY=100, 50, 10

[17]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 1000

# base中进入jp的概率
WIN_JP_PROBABILITY=0.001
# 赢得的JP的倍数，实际赢得的JP要乘以该值
WIN_JP_MULTIPLE=5000, 100, 50, 20
# 赢得每种JP的概率，相加为总概率
WIN_JP_TYPE_PROBABILITY=1, 5, 100, 500

# free的倍乘
FREE_MULTIPLE=2
# free的倍乘概率，相加为总概率
FREE_MULTIPLE_PROBABILITY=100
# Super free的倍乘
SUPER_FREE_MULTIPLE=6, 8, 15
# super free的倍乘概率，相加为总概率
SUPER_FREE_MULTIPLE_PROBABILITY=100, 50, 10