[MAIN]
#配置文件版本，当版本改变时重新读取配置
version = 103
#下述每个Group中，（单次Spin）砍掉多少倍以上奖励(0不砍)
control_group_cut_multiple = 5000,0,0,0,12000,0,0,0,1000,0,0,0,20,5000,5000,0,0,1000
#下述每个Group中，免费游戏（单次Spin）砍掉多少倍以上奖励(0不砍)
control_group_free_cut_multiple = 5000,0,0,0,12000,0,0,0,1000,0,0,0,20,5000,5000,0,0,1000

#常规数值为GROUP_0,可理解为现在的Type0
[CONTROL_GROUP_0]
#标签用户控制组权重,最多20个
lable_user_control_group_rate = 10000
#标签用户控制组控制值(control_type*100+control_num),最多20个
lable_user_control_group_value = 1

[CONTROL_GROUP_1]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 101

[CONTROL_GROUP_2]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 201

[CONTROL_GROUP_3]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 301

[CONTROL_GROUP_4]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 401

[CONTROL_GROUP_5]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 501

[CONTROL_GROUP_6]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 601

[CONTROL_GROUP_7]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 701

[CONTROL_GROUP_8]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 801

[CONTROL_GROUP_9]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 901

[CONTROL_GROUP_10]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1001

[CONTROL_GROUP_11]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1101

[CONTROL_GROUP_12]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1201

[CONTROL_GROUP_13]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1301

[CONTROL_GROUP_14]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1401

[CONTROL_GROUP_15]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1501

[CONTROL_GROUP_16]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1601

[CONTROL_GROUP_17]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1701

[CONTROL_GROUP_18]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1801

[CONTROL_GROUP_19]
lable_user_control_group_rate = 10000
lable_user_control_group_value = 1901
