[Game_Info]
#长时间未操作踢出时间(秒)
kick_time = 180
#多少局计费一次
radius_num = 1500
#砍掉多少倍以上奖励(0不砍)
cut_multiple = 0
#免费游戏砍掉多少倍以上奖励(0不砍)
free_cut_multiple = 0
#限制登陆类型(-1:全部 0:PC 1:Android 2:IOS)
limit_login_type = -1
#限制注册时间(注册时间大于配置时间使用新限制等级)
limit_reg_time = 2024/02/01 00:00:01
#限制等级
limit_lv = 5,5
#限制VIP
limit_vip = 0
#游戏间隔时间(毫秒)
game_gap_time = 300
#合并LOG数(类型相同的时候X局记录一次LOG)  
merge_log_num = 1
#日玩游戏局数(分3段,每段提示,最后一段禁止)
day_play_game_num = 18000,36000,72000
#限制发送公告用户类型(-1:不限制 0:限制游客)
limit_send_bull_user_type = 0
#限制登录标签用户值,对应数据库刷分标签值,最多20个
limit_login_lable_user_value = 1,40,41,42,43,44,45
#限制登录标签用户进入游戏提示维护几率-万分比
limit_login_lable_user_percent = 0
#最小活动版本号 2.29是8 
daily_act_game_ver = 8


#回放功能开关 0关闭 1开启
replay_open = 0
#回放排行最小金币数（设定为3B）
replay_min_win_money = 3000000000
#回放排行最小倍数
replay_min_win_mul = 999999
#回放最小功能版本
replay_min_version = 65

#服务器任务开关（0关1开，默认为关）
task_open = 1
#无任务标签（account_shua_02，默认为0，大于0才生效，配置的标签用户不能累计任务）
task_skip_label_value = 0