[System Base Info]
#活动币掉落 是否开启 0-关闭，1-开启
if_start = 1
#活动币开始掉落时间(游戏服务器时间-格林威治时间)
start_time = 2026/06/08 06:30:00
#活动币结束掉落时间
end_time = 2026/07/20 16:59:59
#最大发放活动币个数（身上活动币数）
max_num = 50000
#发放概率(万分比)
send_rate = 8000
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#首次强发时间(秒)（如果在下面时间内没有获得就直接掉落活动币）
max_limit_time0 = 40
#强发时间(秒)（如果在下面时间内没有获得就直接掉落活动币）
max_limit_time = 100
#缓存计费活动币数目（达到了就计费一次）
must_radius_get_num = 100

#分段控制活动币掉落(最多5段，根据今日获得活动币数目，最后一个值是控制今日获得最大上限大于该值获得几率为0)
section_activity_num = 10,50,100,250,500
#每段有3种掉落概率和数目（概率为百分比）
#第1段配置
#掉落概率
section_send_rate_1 = 20,8,72
#掉落活动币数量
section_send_num_1 = 3,2,0
#第2段配置
section_send_rate_2 = 16,12,72
section_send_num_2 = 3,2,0
#第3段配置
section_send_rate_3 = 16,12,72
section_send_num_3 = 2,1,0
#第4段配置
section_send_rate_4 = 12,8,80
section_send_num_4 = 2,1,0
#第5段配置
section_send_rate_5 = 8,8,84
section_send_num_5 = 2,1,0

#正对渠道开放活动配置,(配为0表示所有渠道都开发，针对多个渠道配置：1000,1002010,100023)
start_agent_id = 0

[game_on_time_show_ico]
#游戏定时显示ico(有显示ico功能，可以提前打开入口预热)
#是否显示，0不显示，1显示(根据客户端game_activity.conf文件activity_sh_type参数决定审核地区是否显示)
if_show = 0
#显示第几个"Tips内容"(值为0,1)
show_tips_index = 1
#开始时间
game_start_time = 2026/06/08 06:30:00
#结束时间
game_end_time = 2026/07/20 16:59:59

[game_ico_show]
#客户端跳转类型，0就是关闭ico显示 1是内嵌，2是外链，3是弹Tips，4是活动引导图片
game_client_show_type = 4
#客户端活动图标ico名称
game_client_ico = sbhd_icon.png
#跳转url的类型
game_client_show_url = sbhd_db.png
#Tips 内容  tips0暂未启用
game_client_tips0_0 = Setiap ronde game selesai ada peluang mendapat koin event!
game_client_tips0_1 = Have chances to earn event coins after each round!
game_client_tips0_2 = Setiap ronde game selesai ada peluang mendapat koin event!

game_client_tips1_0 = Setiap ronde game selesai ada peluang mendapat koin event!
game_client_tips1_1 = Have chances to earn event coins after each round!
game_client_tips1_2 = Setiap ronde game selesai ada peluang mendapat koin event!
#内嵌活动页面标题
game_client_tile = Event merdeka Lucky Slots

[game_start_act]
#开启那些活动，Ico显示优先级按照顺序: 活动ID,是否显示|活动ID,是否显示
all_start_act_info =30,1
