[System Base Info]
#成就是否开启0是关闭
if_start = 1

[game_achievement]
#开启了哪些成就: 成就ID,是否开启|活动ID,是否开启
all_ach_info = 301,1|302,1|303,1|304,1|305,1|306,1|307,1|308,1|309,1|310,1|311,1|312,1|313,1|314,1|315,1|316,1|317,1|318,1|319,1|320,1|321,1|322,1|323,1|324,1

no_supported_player = 1,40,41,42,43,44,45,61,62,21

# 0中文，1英文，2印尼语
[0]
ach_name_301 = 财神手
ach_name_302 = 一押暴富
ach_name_303 = 旋转大师
ach_name_304 = 愈押愈富
ach_name_305 = 免费赢家
ach_name_306 = 一押巨富
ach_name_307 = 豪赌侠客
ach_name_308 = 消除达人
ach_name_309 = 家财万贯
ach_name_310 = 一押豪中
ach_name_311 = 豪赌大神
ach_name_312 = 免费赢家
ach_name_313 = 好运连连
ach_name_314 = 大赢家
ach_name_315 = 一押巅峰
ach_name_316 = MEGA赢家
ach_name_317 = SUPER赢家
ach_name_318 = EPIC赢家
ach_name_319 = ULTRA赢家
ach_name_320 = 豪赌贵族
ach_name_321 = 分散收藏家
ach_name_322 = 彩金大师
ach_name_323 = 连线大神
ach_name_324 = 免费风暴

[1]
ach_name_301 = God's Hand
ach_name_302 = Instant Fortune
ach_name_303 = SPIN Master
ach_name_304 = Bet Addict
ach_name_305 = Free Spins Master
ach_name_306 = Betting King
ach_name_307 = Daredevil Bet
ach_name_308 = The Eliminator
ach_name_309 = Prince of Wealth
ach_name_310 = Lucky Betting
ach_name_311 = Bet God
ach_name_312 = Freebies Win
ach_name_313 = The Luckiest
ach_name_314 = Big Winner
ach_name_315 = Ultimate Bet
ach_name_316 = Lucky Winner
ach_name_317 = Super Winner
ach_name_318 = Master Winner
ach_name_319 = God Winner
ach_name_320 = Eternal Bet
ach_name_321 = Scatter King
ach_name_322 = Master Jackpot
ach_name_323 = Line Master
ach_name_324 = King of Freebies

[2]
ach_name_301 = Tangan Dewa
ach_name_302 = Kaya Mendadak
ach_name_303 = Master SPIN
ach_name_304 = Penggila Bet
ach_name_305 = Master Gratisan
ach_name_306 = Raja Bet
ach_name_307 = Pemberani Bet
ach_name_308 = Sang Eliminator
ach_name_309 = Pangeran Kekayaan
ach_name_310 = Bet Hoki
ach_name_311 = Dewa Bet
ach_name_312 = Menang Gratisan
ach_name_313 = Si Paling Hoki
ach_name_314 = Pemenang Besar
ach_name_315 = Bet Tertinggi
ach_name_316 = Pemenang Hoki
ach_name_317 = Pemenang Super
ach_name_318 = Pemenang Master
ach_name_319 = Pemenang Dewa
ach_name_320 = Bet Abadi
ach_name_321 = Raja Scatter
ach_name_322 = Master Jackpot
ach_name_323 = Ahli Garis
ach_name_324 = Extra FREE SPINS