[DROP_CONF]
#配置文件版本，当版本改变时重新读取配置
VERSION = 113
#是否开启（0:关闭,1:开启）
IF_START = 1
#是否通知任务进度（0:不通知,1:通知）
IF_NOTICE = 0
#缓存计费数量
RADIUS_NUM = 99
#最大发放个数
MAX_NUM = 99
#基础玩分，超出基础玩法部分通过公式衰减
#玩分转换分数公式:((baseplaymoney+((playmoney-baseplaymoney)*baseplaymoney/playmoney))*scoreaccumrate/10000)
BASE_PLAY_MONEY = 50000000
#超出基础玩分部分按比例累计（万分比）
SCORE_ACCUM_RATE = 10000

[DROP_INFO_1]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 1000000

[DROP_INFO_2]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 2000000

[DROP_INFO_3]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 3000000

[DROP_INFO_4]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 5000000

[DROP_INFO_5]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 10000000

[DROP_INFO_6]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 20000000

[DROP_INFO_7]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 25000000

[DROP_INFO_8]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 30000000

[DROP_INFO_9]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 40000000

[DROP_INFO_10]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 50000000

[DROP_INFO_11]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 80000000

[DROP_INFO_12]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 120000000

[DROP_INFO_13]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 200000000

[DROP_INFO_14]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 500000000

[DROP_INFO_15]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 1000000000

[DROP_INFO_16]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 2000000000

[DROP_INFO_17]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 3000000000

[DROP_INFO_18]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 5000000000

[DROP_INFO_19]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 10000000000

[DROP_INFO_20]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 20000000000

[DROP_INFO_21]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 30000000000

[DROP_INFO_22]
#掉落数量
DROP_NUM = 1
#掉落所需分数
DROP_SCORE = 50000000000
