[10008]
#活动币发放数量
drop_coin_num = 1
#最大发放活动币个数（身上活动币数）
max_num = 99999
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 0
#活动币发放是否通知任务进度（0:不通知,1:通知）
activity_coin_task_notice = 0
#活动币发放的最低押注
activity_coin_drop_min_bet = 10000000
#押注几率(万分比),和押注档对应,满足几率才会触发活动币发放
drop_bet_rate = 1000,1000,1000,1000,1000,1000,1000,1000,1000
#押注几率(万分比),和押注档对应,活动币发放的进度 达到10000才给
drop_bet_progress = 400,800,2000,4000,8000,20000,40000,80000,113000

[10010]
#活动币发放数量
drop_coin_num = 1
#最大发放活动币个数（身上活动币数）
max_num = 99999
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 0
#活动币发放是否通知任务进度（0:不通知,1:通知）
activity_coin_task_notice = 0
#活动币发放的最低押注
activity_coin_drop_min_bet = 10000000
#押注几率(万分比),和押注档对应,满足几率才会触发活动币发放
drop_bet_rate = 1000,1000,1000,1000,1000,1000,1000,1000,10000
#押注几率(万分比),和押注档对应,活动币发放的进度 达到10000才给
drop_bet_progress = 400,800,2000,4000,8000,20000,40000,80000,113000

[10011]
#活动币发放数量
drop_coin_num = 1
#最大发放活动币个数（身上活动币数）
max_num = 99999
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 0
#活动币发放是否通知任务进度（0:不通知,1:通知）
activity_coin_task_notice = 0
#活动币发放的最低押注
activity_coin_drop_min_bet = 10000000
#押注几率(万分比),和押注档对应,满足几率才会触发活动币发放
drop_bet_rate = 10000,10000,10000,10000,10000,10000,10000,10000,10000
#押注几率(万分比),和押注档对应,活动币发放的进度 达到10000才给
drop_bet_progress = 400,800,2000,4000,8000,20000,40000,80000,113000
[10012]
#活动币发放数量
drop_coin_num = 1
#最大发放活动币个数（身上活动币数）
max_num = 99999
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 1
#活动币发放是否通知任务进度（0:不通知,1:通知）
activity_coin_task_notice = 0
#活动币发放的最低押注
activity_coin_drop_min_bet = 10000000
#押注几率(万分比),和押注档对应,满足几率才会触发活动币发放
drop_bet_rate = 1000,1000,1000,1000,1000,1000,1000,1000,1000
#押注几率(万分比),和押注档对应,活动币发放的进度 达到10000才给
drop_bet_progress = 400,800,2000,4000,8000,20000,40000,80000,113000

[10013]
#活动币发放数量
drop_coin_num = 1
#最大发放活动币个数（身上活动币数）
max_num = 99999
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 0
#活动币发放是否通知任务进度（0:不通知,1:通知）
activity_coin_task_notice = 0
#活动币发放的最低押注
activity_coin_drop_min_bet = 10000000
#押注几率(万分比),和押注档对应,满足几率才会触发活动币发放
drop_bet_rate = 1000,1000,1000,1000,1000,1000,1000,1000,1000
#押注几率(万分比),和押注档对应,活动币发放的进度 达到10000才给
drop_bet_progress = 400,800,2000,4000,8000,20000,40000,80000,113000


[10017]
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 1
#冲榜活动强制计费局数
activity_force_send_radius_spin_num = 1
