[System Base Info]
# XML 25档押注安全关闭占位；正式活动配置需从游三工具平台下载
#活动币掉落配置(押注局数+押注几率)
#押注局数(最小,最大),范围内随机,满足押注局数才会触发押注档几率
#押注几率(万分比),和押注档对应,满足几率才会触发底层活动币发放
DropBetRange = 1,2
DropBetRate = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


[Coin Info]
#押注几率(万分比),和押注档对应,满足几率才会触发活动币发放
drop_bet_rate = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
#押注几率(万分比),和押注档对应,活动币发放的进度 达到10000才给
drop_bet_progress = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0