[Act_Double_Info]
#是否开放
if_start = 1
#时差（服务器时间和印尼当地时间差）,用户客户端显示用的
time_difference = 7
#活动开始时间
start_time = 2021/05/22 00:00:00
#活动结束时间
end_time  = 2023/12/22 15:59:59
#每天开放时间段（旧配置，更新完可删除）
#中午奖励翻倍
time_hour_1 = 12-13
#晚上奖励翻倍
time_hour_2 = 0-0

#每天开放时间段(周一--周日)
day_time_1 = 20-21
day_time_2 = 13-14
day_time_3 = 12-13,18-22
day_time_4 = 12-13
day_time_5 = 12-23
day_time_6 = 6-7,16-18
day_time_7 = 6-7,22-23

#活动Ico上面显示的tips内容，内容空就不显示; tips_1每天只有一个时间段显示内容，tips_2是每天多个时间的提示内容,如果内中有时间请考虑时区的问题.
#ico_tips_1 = Double bonus(Senin s/d Jumat 19.00-20.00 WIB)
#ico_tips_2 = Double bonus(13.00-14.00 19.00-21.00 WIB)

ico_tips1_0 = Double bonus(MON-FRI 12.00-13.00 GMT)
ico_tips1_1 = Double bonus(MON-FRI 12.00-13.00 GMT)
ico_tips1_2 = Double bonus(Senin s/d Jumat 19.00-20.00 WIB)
ico_tips1_3 = Double bonus(MON-FRI 12.00-13.00 GMT)

ico_tips2_0 = Double bonus(6.00-7.00 12.00-14.00 GMT)
ico_tips2_1 = Double bonus(6.00-7.00 12.00-14.00 GMT)
ico_tips2_2 = Double bonus(13.00-14.00 19.00-21.00 WIB)
ico_tips2_3 = Double bonus(6.00-7.00 12.00-14.00 GMT)