#公告配置
[bull_info]
#显示那几个游戏的公告(针对多个游戏显示类型公告)
show_bull_gameid = 18,70,71
#元宝大于多少才发送公告
send_bull_yb_min = 300
#金币大于多少才发送公告
send_bull_money_min = 50000000
#金币和元宝对应优先级比例值
jb_yb_priority_rate = 1000000

#服务器提示文字,0中文，1英文，2地方语言
#4是slot公告
#中文配置
[bull_text_type_0]
bull_text_0 = 无
bull_text_1 = 在[$RoomName$]完成任务获得^&*$YBNum$ Rp^&*点券奖励
bull_text_2 = 在[$RoomName$]获得Jackpot ^&*$YBNum$ Rp^&*点券
bull_text_3 = 在[$RoomName$]获得BigWin ^&*$YBNum$ Rp^&*点券
bull_text_4 = 在[$RoomName$]!@获得 ^&*$YBNum$^&*金币

#英文配置
[bull_text_type_1]
bull_text_0 = NULL
bull_text_1 = Complete tasks and get ^&*Rp $YBNum$^&* coupon in[$RoomName$]
bull_text_2 = Win Jackpot and get ^&*Rp $YBNum$^&* coupon in [$RoomName$]
bull_text_3 = Have BigWin and get ^&*Rp $YBNum$^&* coupon in [$RoomName$]
bull_text_4 = Get ^&*$YBNum$^&* coins !@in [$RoomName$]

#地方语言配置（印尼语）
[bull_text_type_2]
bull_text_0 = NULL
bull_text_1 = mendapatkan hadiah kupon ^&*Rp $YBNum$^&* dari misi di [$RoomName$]
bull_text_2 = mendapatkan Jackpot kupon ^&*Rp $YBNum$^&* di [$RoomName$]
bull_text_3 = mendapatkan BigWin kupon ^&*Rp $YBNum$^&* di [$RoomName$]
bull_text_4 = Di[$RoomName$]!@Mendapatkan ^&*$YBNum$^&* Koin


#地方语言配置（马来语）
[bull_text_type_3]
bull_text_0 = NULL
bull_text_1 = Dapat hadiah kupon ^&*Rp$YBNum$^&* dari misi di [$RoomName$]
bull_text_2 = Dapat jackpot kopon ^&*Rp$YBNum$^&* di [$RoomName$]
bull_text_3 = Dapat BigWin kupon ^&*Rp$YBNum$^&* di [$RoomName$]
bull_text_4 = Di[$RoomName$]!@Mendapatkan ^&*$YBNum$^&* Koin