[Game_Get_Exp_Info]
#金币和经验值换算值(1M=N 经验值)
exp_val = 100
#等级限制(小于等于)
lv_limit = 5
#经验值获得比例值（百分比），5级前比例|正常比例|solt用户比例
get_val_rate = 100|100|100

#不能获得等级经验值的等级限制,0-0表示没有限制，关闭该功能
get_val_lv_limit = 3-5
#特殊条件，VIP等级大于等于配置值，解除升级限制
get_val_vip_min = 1

get_play_money_exp_val = 100
