[Coin Info]
#日常活动币掉落配置
#版本号控制是否更新掉落配置
version = 101
#活动id
activity_id = 10010
#活动币掉落 是否开启 0-关闭，1-开启
if_start = 0
#活动币开始掉落时间(游戏服务器时间-格林威治时间)
start_time = 2025/11/28 02:00:00
#活动币掉落结束时间
end_time = 2025/12/01 02:00:00
#活动币发放数量
drop_coin_num = 1
#最大发放活动币个数（身上活动币数）
max_num = 99999
#最小游戏局时（秒）（小于这个时间不发放活动币）
min_game_time = 1
#首次强发时间(秒)（如果在下面时间内没有获得就直接掉落活动币）
max_limit_time0 = 0
#强发时间(秒)（如果在下面时间内没有获得就直接掉落活动币）
max_limit_time = 0
#活动最小功能版本号
daily_act_game_ver = 8
#以上为基础活动币掉落配置
#活动币发放规则 0基础掉落 1根据任务掉落
activity_coin_rule = 0
#活动币发放是否通知任务进度（0:不通知,1:通知）
activity_coin_task_notice = 0
#活动币发放的最低押注
activity_coin_drop_min_bet = 0