[System Base Info]
#相同配置
AutoSpinTimes = 10,100,500,-1,-2
#第四个参数为super洗分匀速到加速的临界值
BigWinGrade = 10,20,50
NewBigWinGrade = 5,10,20,50,100,500
BetPerReel = 10,10,10,10,10,10,10,10,10
BetScopes = 10,20,50,100,200,500,1000,2000,2500
#解锁押注配置(注册时间+玩家等级+玩家VIP等级)
#解锁押注注册时间,在此时间之后注册的才走配置
#解锁押注玩家等级,达到等级解锁(VIP等级满足此项不生效)
#解锁押注玩家VIP等级,达到等级解锁(不需要判断玩家等级)
BetUnLockRegTime = 2000/09/09 08:00:00
BetUnLockLevel = 5,5,5,5,5,5,5,5,0
BetUnLockVip = 0,0,0,0,0,0,0,0,2

[Game Info]
#版本号，每次改变下面配置需要改变
Version=107

#赢分框升级倍数,填写赢分框升级到第2、3状态的总倍数
WinBoxLevelMultiple=3,5
#免费游戏最大次数 ,不允许超过该次数
FreeMaxGameNum = 99
#主游戏最大消除次数，不允许超过该消除次数（如果为0则不砍分）
MainMaxRoundNum = 10
#免费游戏最大消除次数，不允许超过该消除次数（如果为0则不砍分）
FreeMaxRoundNum = 10
#黑色Scatter赔付倍数 【一个、两个、三个、四个及以上】
BlackScatterWinMult = 50,500,5000,100000
#根据档位走不同[GENERAL_]滚轮
BetGeneralCtrl =1,1,1,1,1,1,1,1,1,1,1,1
 
[0]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 5000
#不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比）
GoldSymbolWeight =750,600,730
#免费游戏不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比），免费游戏第三列固定位10000
FreeGoldSymbolWeight =600,10000,690
#Scatter 转化为黑色Scatter的概率 【零个、一个....】(万分比)
BlackScatterWeight = 1000,1000,1500,0
#未中奖时，额外黑龙生成概率 转化为黑色Scatter的概率 【零个、一个】(万分比)
ExtraBlackScatterWeight = 2000,1000

[4]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 10000
#不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比）
GoldSymbolWeight =750,600,730
#免费游戏不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比），免费游戏第三列固定位10000
FreeGoldSymbolWeight =600,10000,690
#Scatter 转化为黑色Scatter的概率 【零个、一个....】(万分比)
BlackScatterWeight = 1000,1000,1500,0
#未中奖时，额外黑龙生成概率 转化为黑色Scatter的概率 【零个、一个】(万分比)
ExtraBlackScatterWeight = 2000,1000

[8]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 101
#不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比）
GoldSymbolWeight =300,1000,300
#免费游戏不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比），免费游戏第三列固定位10000
FreeGoldSymbolWeight =400,10000,350
#Scatter 转化为黑色Scatter的概率 【零个、一个....四个】(万分比)
BlackScatterWeight = 0,0,0,0
#未中奖时，额外黑龙生成概率 转化为黑色Scatter的概率 【零个、一个】(万分比)
ExtraBlackScatterWeight = 2000,1000

[12]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 20
#不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比）
GoldSymbolWeight =100,200,100
#免费游戏不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比），免费游戏第三列固定位10000
FreeGoldSymbolWeight =200,10000,200
#Scatter 转化为黑色Scatter的概率 【零个、一个....】(万分比)
BlackScatterWeight = 0,0,0,0
#未中奖时，额外黑龙生成概率 转化为黑色Scatter的概率 【零个、一个】(万分比)
ExtraBlackScatterWeight = 2000,1000

[17]
#免费游戏总赢分倍数（如果为0则不砍分）
FreeMaxTotalBet = 1000
#不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比）
GoldSymbolWeight =750,600,730
#免费游戏不同列变成金色的概率【第二列，第三列，第四列】（每列独立万分比），免费游戏第三列固定位10000
FreeGoldSymbolWeight =300,10000,500
#Scatter 转化为黑色Scatter的概率 【零个、一个....四个】(万分比)
BlackScatterWeight = 0,0,0,0
#未中奖时，额外黑龙生成概率 转化为黑色Scatter的概率 【零个、一个】(万分比)
ExtraBlackScatterWeight = 2000,1000